### PR TITLE
Fix integration with platformio

### PR DESCRIPTION
**Pull request by gldhnchn**
Add dependencies to library.json. This will maybe solve issue https://github.com/chrisjoyce911/esp32FOTA/issues/90.

### CODE REVIEW

**Comment by tobozo** [comment]
@gldhnchn thanks !

Can you specify what OS/pio version this was failing on so I can extend the CI tests?

**Comment by gldhnchn** [comment]
Yes, of course. But I guess this would have failed on every OS with platformio. Am I wrong?
```
$ platformio --version
PlatformIO Core, version 6.1.4
$ lsb_release -a
LSB Version:	core-11.1.0ubuntu4-noarch:printing-11.1.0ubuntu4-noarch:security-11.1.0ubuntu4-noarch
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.1 LTS
Release:	22.04
Codename:	jammy
```

**Comment by tobozo** [comment]
looks like both the workflow and the platformio.ini need an update.

I'll look into that before producing a new release.

thanks for your precious feedback ! :+1:

**Comment by tobozo** [comment]
the CI could [reproduce the error](https://github.com/chrisjoyce911/esp32FOTA/actions/runs/3127300603/jobs/5073774993), and a fix is ready, new release coming soon :-)

**Pull request merged**
